version: "3"
services:
  db:
    container_name: BasedeDatos
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: practicas
      MYSQL_DATABASE: Prueba
      MYSQL_USER: root
      MYSQL_PASSWORD: practicas
    ports:
     -"3306:3306"
    expose:
    - '3306'
    volumes:
      -./var/lib/docker/volumes/Practica/_data