version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: practicas
      MYSQL_DATABASE: mysql_docker
      MYSQL_USER: root@localhost
      MYSQL_PASSWORD: practicas
    ports:
     -"3306:3306"